In [2]:
import numpy as np

取亂數
形成陣列


In [8]:
rnum=int(input())
cnum=int(input())
data=np.random.random((rnum,cnum))
data

3
4


In [16]:
std=np.std(data)
print(std)
print(data.T)

0.308580658424
[[ 0.93100118  0.1722608   0.53099927]
 [ 0.42217428  0.05426777  0.93596715]
 [ 0.89525722  0.80926582  0.59119584]
 [ 0.08226031  0.55265861  0.74421294]]
